// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA140hlAtvksrowSLs2aaGDXAsJYujFKOg',
    appId: '1:318946402557:web:ef2e467087c877b7611e94',
    messagingSenderId: '318946402557',
    projectId: 'bookit-d5ccb',
    authDomain: 'bookit-d5ccb.firebaseapp.com',
    storageBucket: 'bookit-d5ccb.firebasestorage.app',
    measurementId: 'G-DEQ6LC9S9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ob2qPBgZlAlXhytZ7xfrq_ogQqJ5qgs',
    appId: '1:318946402557:android:404d1a1dc8c44277611e94',
    messagingSenderId: '318946402557',
    projectId: 'bookit-d5ccb',
    storageBucket: 'bookit-d5ccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATDpFkATnOClchoo6qAi4zpdlU6bFc__4',
    appId: '1:318946402557:ios:5c17f972e3acc96f611e94',
    messagingSenderId: '318946402557',
    projectId: 'bookit-d5ccb',
    storageBucket: 'bookit-d5ccb.firebasestorage.app',
    iosBundleId: 'com.example.bookitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATDpFkATnOClchoo6qAi4zpdlU6bFc__4',
    appId: '1:318946402557:ios:5c17f972e3acc96f611e94',
    messagingSenderId: '318946402557',
    projectId: 'bookit-d5ccb',
    storageBucket: 'bookit-d5ccb.firebasestorage.app',
    iosBundleId: 'com.example.bookitApp',
  );
}
